/*
 * This software is being provided for technology demonstration purposes only.
 * Use of Vaadin Touchkit Add-on API are provided via Affero General Public License
 * (APGL 3.0).  Please refer the APGL 3.0 at www.gnu.org for further details.
 *
 * Items outside of the use of Vaadin Touchkit Add-on API are being provided per
 * FARS 52.227-14 Rights in Data - General.  Any redistribution or request for
 * copyright requires written consent by the Department of Veterans Affairs.
 */
function RV(){}
function MV(){}
function Ixb(){}
function Hxb(){}
function hGb(d,b){var c=d;b.notifyChildrenOfSizeChange=Opc(function(){c.of()})}
function pGb(c){try{c!=null&&eval('{ var document = $doc; var window = $wnd; '+c+twc)}catch(b){}}
function eGb(b){var c,d,e;e=b.Ob.getElementsByTagName(yyc);for(c=0;c<e.length;++c){d=e[c];DZ();QZ(d,32768)}}
function dGb(c){if(c&&c.iLayoutJS){try{c.iLayoutJS();return true}catch(b){return false}}else{return false}}
function TV(){PV=new RV;Ub((Sb(),Rb),5);!!$stats&&$stats(xc(Fyc,Xpc,-1,-1));PV.Qc();!!$stats&&$stats(xc(Fyc,$xc,-1,-1))}
function iGb(b,c){var d,e;fjb(b.b,yr(c,26));e=cGb(b,c);e!=null&&b.j.xg(e);d=yr(b.o.vg(c),147);if(d){b.o.xg(c);return E_(b,d)}else if(c){return E_(b,c)}return false}
function cGb(b,c){var d,e,f,g;for(d=(f=Eic(b.j).c.ud(),new Ekc(f));d.b.Sc();){e=yr((g=yr(d.b.Tc(),58),g.Cg()),1);if(Cr(b.j.vg(e))===(c==null?null:c)){return e}}return null}
function QV(){var b,c,d;while(NV){d=nb;NV=NV.b;!NV&&(OV=null);if(!d){(pub(),oub).wg(GC,new Ixb);Jlb()}else{try{(pub(),oub).wg(GC,new Ixb);Jlb()}catch(b){b=oJ(b);if(Ar(b,37)){c=b;Lrb.He(c)}else throw b}}}}
function nqb(c,d){try{if(c.currentStyle){return c.currentStyle[d]}else if(window.getComputedStyle){var e=c.ownerDocument.defaultView;return e.getComputedStyle(c,null).getPropertyValue(d)}else{return Spc}}catch(b){return Spc}}
function kGb(b,c,d){var e,f;if(!c){return}e=zr(b.g.vg(d));if(!e&&!(b.c==null&&!b.e)){throw new Jgc('No location '+d+' found')}f=yr(b.j.vg(d),70);if(f==c){return}!!f&&iGb(b,f);!(b.c==null&&!b.e)||(e=b.Ob);_$(c);u9(b.Ib,c);e.appendChild(c.Ob);b_(c,b);b.j.wg(d,c)}
function gGb(b,c){var d,e,f;if(yhc(b,Spc)||yhc(c,Spc)){return false}if(!(b.lastIndexOf(src)!=-1&&b.lastIndexOf(src)==b.length-src.length)||!(c.lastIndexOf(src)!=-1&&c.lastIndexOf(src)==c.length-src.length)){return false}f=ogc(b.substr(0,b.length-2-0));d=ogc(c.substr(0,c.length-2-0));e=f>d;return e}
function mGb(){this.Ib=new A9(this);this.g=new Dnc;this.j=new Dnc;this.o=new Dnc;this.i=new Dnc;this.Ob=$doc.createElement(Qrc);this.Ob.style[Ktc]=rqc;this.Ob.style[Kyc]=Zqc;this.Ob.style[guc]=Zqc;(Umb(),!Tmb&&(Tmb=new qnb),Umb(),Tmb).b.i&&(this.Ob.style[iqc]=vtc,undefined);this.Ob[trc]='v-customlayout'}
function jGb(b,c){var d,e,f,g,i,k,n,o,p,q;g=c.getAttribute(Jyc)||Spc;if(yhc(Spc,g)){f=MZ(c);for(e=0;e<f;++e){jGb(b,LZ(c,e))}}else{b.g.wg(g,c);c.innerHTML=Spc;i=Dqb(c,0);k=(bqb(),n=c.style[Arc],o=c.offsetHeight||0,q=o,o<1&&(q=1),c.style[Arc]=q+src,p=(c.offsetHeight||0)-q,c.style[Arc]=n,p);d=new _ob(i,k);b.i.wg(g,d)}}
function lGb(b,c,d){var e,f,g,i,k,n,o,p;f=new Lnc;for(i=(k=Gic(b.j).c.ud(),new Qkc(k));i.b.Sc();){g=yr(yr(i.b.Tc(),58).Dg(),70);e=b.b.t[g.Ob.tkPid].f;if(e){if(c&&e.c>=0||d&&e.b>=0){n=f.b.wg(g,f);g.Ob.style[iqc]=lqc}}}for(i=(o=Eic(f.b).c.ud(),new Ekc(o));i.b.Sc();){g=yr((p=yr(i.b.Tc(),58),p.Cg()),70);Mib(b.b,g);g.Ob.style[iqc]=Spc}}
function bGb(b,c){var d,e,f,g,i,k,n,o;c=Ahc(c,'_UID_',b.k+'__');b.n=Spc;e=0;g=c.toLowerCase();k=Spc;n=g.indexOf(Gyc,0);while(n>0){k+=c.substr(e,n-e);n=g.indexOf(Bvc,n);f=g.indexOf('<\/script>',n);b.n+=c.substr(n+1,f-(n+1))+Ovc;i=e=f+9;n=g.indexOf(Gyc,i)}k+=c.substr(e,c.length-e);c=k;g=k.toLowerCase();o=g.indexOf('<body');if(o<0){k=k}else{o=g.indexOf(Bvc,o)+1;d=g.indexOf('<\/body>',o);d>o?(k=c.substr(o,d-o)):(k=c.substr(o,c.length-o))}return k}
function fGb(b,c,d){var e,f,g,i,k;f=c[1]['templateContents'];e=c[1]['template'];b.c=null;b.e=false;if(e!=null){i=yr(d.E.vg('layouts/'+e+'.html'),1);i==null?(i='<em>Layout file layouts/'+e+'.html is missing. Components will be drawn for debug purposes.<\/em>'):(b.c=e)}else{b.e=true;i=f}i=bGb(b,i);k=d.p.q;g=k+'/layouts/';i=Ahc(i,'<((?:img)|(?:IMG))\\s([^>]*)src="((?![a-z]+:)[^/][^"]+)"',Hyc+g+Iyc);i=Ahc(i,'<((?:img)|(?:IMG))\\s([^>]*)src=[^"]((?![a-z]+:)[^/][^ />]+)[ />]',Hyc+g+Iyc);i=Ahc(i,'(<[^>]+style="[^"]*url\\()((?![a-z]+:)[^/][^"]+)(\\)[^>]*>)','$1 '+g+'$2 $3');b.Ob.innerHTML=i||Spc;b.g.sd();jGb(b,b.Ob);eGb(b);b.d=je(b.Ob);!b.d&&(b.d=b.Ob);hGb(b,b.d)}
var Iyc='$3"',Hyc='<$1 $2src="',Gyc='<script',Jyc='location',Fyc='runCallbacks5';_=RV.prototype=MV.prototype=new J;_.gC=function SV(){return lw};_.Qc=function WV(){QV()};_.cM={};_=Ixb.prototype=Hxb.prototype=new J;_.Ue=function Jxb(){return new mGb};_.gC=function Kxb(){return uB};_.cM={137:1};_=mGb.prototype=aGb.prototype;_.rd=function nGb(b){throw new kic};_.je=function qGb(b){var c,d,e,f;d=(e=b.Ob.parentNode,(!e||e.nodeType!=1)&&(e=null),e);c=yr(this.i.vg(cGb(this,b)),148);return new npb((d.offsetWidth||0)-~~Math.max(Math.min(c.c,2147483647),-2147483648),(d.offsetHeight||0)-~~Math.max(Math.min(c.b,2147483647),-2147483648),(bqb(),f=nqb(d,msc),f!=null&&(yhc(f,Isc)||yhc(f,Kqc))))};_.gC=function rGb(){return GC};_.Me=function sGb(){dGb(je(this.Ob))};_.of=function tGb(){Zib(this.b,this)};_.Vc=function uGb(b){Z$(this,b);if(CZ(b.type)==32768){Gqb(this,true);b.cancelBubble=true}};_.nd=function vGb(){$$(this);!!this.d&&(this.d.notifyChildrenOfSizeChange=null,undefined)};_.td=function wGb(b){return iGb(this,b)};_.ke=function xGb(b,c){var d;d=cGb(this,b);if(d==null){throw new Igc}kGb(this,c,d)};_.le=function yGb(b){lGb(this,true,true);if(yhc(this.p,Spc)||yhc(this.f,Spc)){return false}return true};_.dd=function zGb(b){var c;if(yhc(this.f,b)){return}c=true;gGb(b,this.f)&&(c=false);this.f=b;this.Ob.style[Arc]=b;c&&lGb(this,false,true)};_.gd=function AGb(b){var c;if(yhc(this.p,b)){return}c=true;gGb(b,this.p)&&(c=false);this.Ob.style[vrc]=b;this.p=b;c&&lGb(this,true,false)};_.me=function BGb(b,c){var d,e;e=yr(this.o.vg(b),147);if(Erb(c)){if(!e){d=cGb(this,yr(b,70));E_(this,yr(b,70));e=new Jrb(b,this.b);w_(this,e,zr(this.g.vg(d)));this.o.wg(b,e)}e.b.Te(c);e.Ob.style.display=!Boolean(c[1][Gtc])?Spc:rqc}else{if(e){d=cGb(this,yr(b,70));E_(this,e);w_(this,yr(e.c,70),zr(this.g.vg(d)));this.o.xg(b)}}};_.fe=function CGb(c,d){var b,e,f,g,i,k,n,o,p,q,r;this.b=d;if(gjb(d,this,c,true)){return}this.k=c[1][Mrc];!(this.c==null&&!this.e)||fGb(this,c,d);pGb(this.n);this.n=null;dGb(je(this.Ob));Zib(d,this);n=new Lnc;n.mg(Gic(this.j));for(f=new Tpb(c);p=f.c.length-2,p>f.b+1;){o=zr(Spb(f));if(yhc(o[0],Jyc)){i=o[1][bqc];e=Hib(d,o[2]);try{kGb(this,yr(e,70),i);e.fe(o[2],d)}catch(b){b=oJ(b);if(!Ar(b,146))throw b}n.b.xg(e)!=null}}for(g=(q=Eic(n.b).c.ud(),new Ekc(q));g.b.Sc();){k=yr((r=yr(g.b.Tc(),58),r.Cg()),70);k.ld()&&iGb(this,k)}dGb(je(this.Ob));Zib(d,this)};var lw=dgc(Lxc,'AsyncLoader5'),uB=dgc(Vxc,'WidgetMapImpl$5$1');Opc(TV)();